<?php

namespace ReclamationBundle\Repository;

/**
 * ReclamationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReclamationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findDQL()
    {
        $dqlresult = $this->getEntityManager()
            ->createQuery("SELECT r
                               FROM ReclamationBundle:Reclamation r
                               WHERE r.corbeille= 0
                               AND   r.archive= 0
                              ");
        return $dqlresult->getResult();
    }

    public function RechercheDQL($champ,$id)
    {
        $dqlresult = $this->getEntityManager()
            ->createQuery("SELECT r
                               FROM ReclamationBundle:Reclamation r
                               WHERE r.'$champ'= '$id'
                              ");
        return $dqlresult->getResult();
    }


    public function findEventDQL($id)
    {
        $dqlresult = $this->getEntityManager()
            ->createQuery("SELECT r
                               FROM EventBundle:Evenement_Participant r
                               WHERE r.idParticipant= '$id'
                              ");
        return $dqlresult->getResult();
    }

    public function findOrganisateurDQL($id)
    {
        $dqlresult = $this->getEntityManager()
            ->createQuery("SELECT org
                               FROM 
                                    EventBundle:Evenement_Participant r, 
                                    EventBundle:Event e, 
                                    UserBundle:User org
                               WHERE
                                    r.idParticipant = '$id'
                               AND  e.id = r.idEvent   
                               AND  org.id = e.idorganisateur      
                              ");
        return $dqlresult->getResult();
    }



}
