<?php

namespace ReclamationBundle\Repository;

/**
 * ReclamationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReclamationRepository extends \Doctrine\ORM\EntityRepository
{
    public function RechercheDQL($champ,$id)
    {
        $dqlresult = $this->getEntityManager()
            ->createQuery("SELECT r
                               FROM ReclamationBundle:Reclamation r
                               WHERE r.'$champ'= '$id'
                              ");
        return $dqlresult->getResult();
    }

    public function findDQL($id)
    {
        $dqlresult = $this->getEntityManager()
            ->createQuery("SELECT r
                               FROM ReclamationBundle:Reclamation r
                               WHERE r.corbeille= '$id'
                               AND r.archive='$id'
                              ");
        return $dqlresult->getResult();
    }
}
