<?php

namespace ReclamationBundle\Repository;

/**
 * TypeReclamationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeReclamationRepository extends \Doctrine\ORM\EntityRepository
{
}
