<?php

namespace EventBundle\Repository;

use EventBundle\Entity\Event;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{
    public function createFindAllQuery()
    {
        return $this->_em->getRepository('EventBundle:Event')->createQueryBuilder('E');
    }
}
