<?php

namespace EventBundle\Repository;

/**
 * Evenement_ParticipantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Evenement_ParticipantRepository extends \Doctrine\ORM\EntityRepository
{
}
