<?php

namespace EventBundle\Repository;

/**
 * eventtypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class eventtypeRepository extends \Doctrine\ORM\EntityRepository
{
}
