<?php

namespace EventBundle\Repository;

use EventBundle\Entity\Event;

/**
 * reviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class reviewRepository extends \Doctrine\ORM\EntityRepository
{
    public function mRate(Event $event){
        $conn = $this->getEntityManager()
            ->getConnection();
        $sql = 'SELECT AVG(rate) as rate
      FROM review 
      WHERE idevent = :eid
      GROUP BY idevent ';

        $stmt = $conn->prepare($sql);
        $stmt->execute(array('eid' => $event->getId()));
        return $stmt->fetch();








       /* $query = $this->getEntityManager()
            ->createQuery('SELECT AVG(review.score) as avg_rating
      FROM review 
      WHERE idevent = :eid
      GROUP BY :eid ')
            ->setParameter('eid',$event->getId());
        return $query->getResult();*/
    }
}
