<?php

namespace EventBundle\Repository;

/**
 * reviewlikeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class reviewlikeRepository extends \Doctrine\ORM\EntityRepository
{
}
