<?php

namespace CommunicationBundle\Repository;

/**
 * CategorieForumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieForumRepository extends \Doctrine\ORM\EntityRepository
{
}
