<?php

namespace CommunicationBundle\Repository;

/**
 * Catégorie_ForumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Catégorie_ForumRepository extends \Doctrine\ORM\EntityRepository
{
}
