<?php

namespace CommunicationBundle\Repository;

/**
 * QuestionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionsRepository extends \Doctrine\ORM\EntityRepository
{
    public function createFindAllQuery()
    {
        return $this->_em->getRepository('CommunicationBundle:Questions')->createQueryBuilder('q');
    }
}
