<?php

namespace CommunicationBundle\Repository;

/**
 * ReponsesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReponsesRepository extends \Doctrine\ORM\EntityRepository
{
}
