<?php

namespace CommunicationBundle\Repository;

/**
 * RéponsesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RéponsesRepository extends \Doctrine\ORM\EntityRepository
{
}
