<?php

namespace ProfilingBundle\Repository;

/**
 * CategorieInteretRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieInteretRepository extends \Doctrine\ORM\EntityRepository
{
}
