<?php

namespace ProfilingBundle\Repository;

use Doctrine\ORM\Query;

/**
 * InteretRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InteretRepository extends \Doctrine\ORM\EntityRepository
{
    public function searchByInteret($categorie)
    {
        $dql=$this->getEntityManager();
        $query=$dql->createQuery("SELECT u FROM ProfilingBundle:Interet u join u.categorie c WHERE c.nom LIKE '$categorie%'");
        return $query->getResult(Query::HYDRATE_ARRAY);
    }



    public function intoArray()
    {
        $dql=$this->getEntityManager();
        $query=$dql->createQuery('SELECT m from ProfilingBundle:Interet m');
        $result=$query->getResult(Query::HYDRATE_ARRAY);
        return $result;
    }

}
