<?php

namespace ReservationBundle\Repository;

/**
 * BilletRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BilletRepository extends \Doctrine\ORM\EntityRepository
{
    public function myfindall($code){
        $dqlresult=$this->getEntityManager()
            ->createQuery("SELECT m FROM ReservationBundle:Billet m WHERE m.code='$code'");
        return $dqlresult->getResult();
    }

}
