<?php

namespace NotificationBundle\Repository;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends \Doctrine\ORM\EntityRepository
{

    public function rechercheDQL($champ,$id)
    {
        $dqlresult = $this->getEntityManager()
            ->createQuery("SELECT r
                               FROM NotificationBundle:Notification r
                                WHERE r.'$champ'= '$id'
                              ");
        return $dqlresult->getResult();
    }
    public function updateDQL()
    {
        $dqlQuery = $this->getEntityManager()
                          ->createQueryBuilder()->UPDATE('NotificationBundle:Notification' ,'r')
                                                ->SET('r.seen', 1)
                                                ->WHERE('r.seen = 0 ')
                                                ->getQuery();
         $dqlQuery->execute();
    }


}
