<?php

namespace BlogBundle\Repository;

/**
 * MotscensureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MotscensureRepository extends \Doctrine\ORM\EntityRepository
{
}
