<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXgywnbt\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXgywnbt/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerXgywnbt.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerXgywnbt\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerXgywnbt\appProdProjectContainer(array(
    'container.build_hash' => 'Xgywnbt',
    'container.build_id' => '8291451c',
    'container.build_time' => 1549919848,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerXgywnbt');
